// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BarcodeScannerController from "./barcode_scanner_controller"
application.register("barcode-scanner", BarcodeScannerController)

import ImageDetectionController from "./image_detection_controller"
application.register("image-detection", ImageDetectionController)

import IngredientsController from "./ingredients_controller"
application.register("ingredients", IngredientsController)

import RecipeSearchController from "./recipe_search_controller"
application.register("recipe-search", RecipeSearchController)

import FridgeDisplayController from "./fridge_display_controller"
application.register("fridge-display", FridgeDisplayController)

import RecipeOptionsController from "./recipe_options_controller"
application.register("recipe-options", RecipeOptionsController)
