inherit_gem:
  renuocop: config/base.yml

require:
  - rubocop-capybara
  - rubocop-factory_bot

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

RSpec/ExampleLength:
  Enabled: false

# most likely you would like to copy and adjust the `AllCops` part (e.g. to exclude vendor-files)
# AllCops:
#   NewCops: enable
#   Exclude:
#     - 'vendor/**/*'
#     ... and add all the exclusions from the `config/base.yml`
